### ISSUE TITLE
სიის აღების ფუნქცია

### ISSUE THREAD

**Issue by akhut13** [akhut13/3Line#1]
სიის აღების ფუნქცია დატის ექსელში ექსპორტს გულისხმობს?

**Comment by akhut13** [comment]
სიის აღების ფუნქცია დატის ექსელში ექსპორტს გულისხმობს?

**Comment by davidgabrichidze** [comment]
არა, უბრალოდ დაბრუნებას სერვისიდან

**Comment by akhut13** [comment]
:დდ უი მადლობა, ისე გავიგე თითქოს რაიმე დამატებით ფუნქციონალს მოითხოვდა.
